ui_print "**************************************************"
ui_print "           Oxygen12 Tweak by SthomsonPL           "
ui_print "                 Version: 2.0                     "
ui_print "**************************************************"
ui_print "                   Feautures:                     "
ui_print "-FOD Fix                                          "
ui_print "-Enable Blur on QS                                "
ui_print "-Force High Display Refresh Rate                  "
ui_print "-Enable VoLTE & Wifi Calling                      "
ui_print "-Increase JPEG quality                            "
ui_print "-Improve scrolling                                "
ui_print "-Improve RAM Management                           "
ui_print "-Keep Launcher in RAM                             "
ui_print "-Improve the using experience                     "
ui_print "-Disable share usage data                         "
ui_print "**************************************************"
ui_print "                    Credits:                      "
ui_print "                    NooB9496                      "
ui_print "**************************************************"